.TH lemonbuddy_terminate 1 2016-06-22 "lemonbuddy 1.4.2" "User Manual"
.SH NAME
\fBlemonbuddy_terminate\fR \- Terminate a previous \fBlemonbuddy\fR(1) bar.
.SH SYNOPSIS
.P
lemonbuddy_terminate [noconfirm]
.SH DESCRIPTION
\fBlemonbuddy_terminate\fR is a shell script that sends \fISIGKILL\fR to any currently running instances of \fBlemonbuddy\fR(1) or \fBlemonbar\fR(1).
.TP
.BR noconfirm
If this argument is passed, then the script will not prompt the user before killing.
.SH SEE ALSO
.TP
\fBlemonbar\fR(1), \fBlemonbuddy\fR(1), \fBlemonbuddy_wrapper\fR(1)
