.TH lemonbuddy_wrapper 1 2016-06-22 "lemonbuddy 1.4.2" "User Manual"
.SH NAME
\fBlemonbuddy_wrapper\fR \- Start a \fBlemonbuddy\fR(1) process and connect it to a \fBlemonbar\fR(1) process.
.SH SYNOPSIS
.P
lemonbuddy_wrapper \fIBAR\-NAME\fR
.SH DESCRIPTION
\fBlemonbuddy_wrapper\fR is a shell script that starts \fBlemonbuddy\fR(1) and \fBlemonbar\fR(1) and connects them using a temporary pipe.
.SH ENVIRONMENT
.TP
.BR LEMONBUDDY_EXECUTABLE
Specify an alternate executable to use. The default value is \fIlemonbuddy\fR.
.TP
.BR XDG_CACHE_HOME
The cache directory used by the script. If this variable is not set, then \fI~/.cache\fR is used.
.SH SEE ALSO
.TP
\fBlemonbar\fR(1), \fBlemonbuddy\fR(1), \fBlemonbuddy_terminate\fR(1)
