coverage:
  status:
    project:
      default:
        # Coverage can drop by 0.1% without failing the status
        threshold: 0.1
    patch:
      default:
        # Patches don't need test coverage
        # TODO remove once we have proper testing infrastructure and documentation
        target: 0

ignore:
  - "tests/**/*"
  - "lib/**/*"

comment:
  require_changes: true

github_checks:
    annotations: false
