name: Build Issues
description: Report issues while building polybar from source
labels: ["build", "needs confirmation"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please carefully go through this checklist and check each option.
      options:
        - label: I have followed every step on the [compiling wiki page](https://github.com/polybar/polybar/wiki/Compiling) and installed all necessary dependencies.
          required: true
        - label: My problem is not described on the [known issues page](https://github.com/polybar/polybar/wiki/Known-Issues)
          required: true
        - label: I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem.
          required: true
        - label: I was able to reproduce this build issue in a clean build
          required: true
  - type: dropdown
    id: source
    attributes:
      label: From where are you building polybar?
      options:
        - From a release archive
        - By cloning this repository
        - Some other way (How?)
    validations:
      required: true
  - type: input
    id: how
    attributes:
      label: Describe how you are building polybar.
      description: Only if you selected "Some other way".
      placeholder: ex. polybar from the AUR
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of polybar are you trying to build? If you are building directly from git, this is the output of `git describe --tags`.
      placeholder: ex. 3.5.7
    validations:
      required: true
  - type: textarea
    id: commands
    attributes:
      label: Build Process
      description: List the exact commands you are using to build polybar
      render: shell
      placeholder: |
        mkdir build
        cd build
        cmake ..
        ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Build log
      description: |
        Copy-paste all the terminal output produced while building polybar.
        This MUST include the output of the `cmake`, `make`, and/or `build.sh` commands, if you used them.
      render: text
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      placeholder: ex. Ubuntu 21.04
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context that you think is necessary about the problem here
    validations:
      required: false
