#!/usr/bin/env bash

if [[ "$1" != "noconfirm" ]]; then
  read -p "Send SIGKILL to terminate processes? [Y/n] " -r choice

  [[ "${choice^^}" == "Y" ]] || {
    echo "Aborting..."; exit
  }
fi

pgrep -f "(lemonbuddy_wrapper|^lemonb(uddy|ar))" | xargs kill -9 >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
  echo "Kill signals successfully sent"
else
  echo "Failed to send kill signal ($?)"
fi
